### ISSUE TITLE
Please change bugtracker link

### ISSUE THREAD

**Issue by pcav** [gis-support/gis-support-plugin#3]
It currently points to the repo, not to the issues page.
Thanks.

**Comment by gis-support** [comment]
Thanks, fixed in 9399ea759c301a5bcb85d2493cbaeacff2355a66.

**Comment by pcav** [comment]
apparently still wrong: https://plugins.qgis.org/plugins/gissupport_plugin/
Please note that we are migrating the server where the plugin webapp lives, so better wait until this is finished before uploading a new version.
Thanks.

**Comment by gis-support** [comment]
Were working on other issues that you reported so we didn't uploded new version yet. Thanks for information about server migration, are there any status or info page about when it will be finished?

**Comment by pcav** [comment]
It should be announced on qgis-dev
